src/main.go

This commit includes how to get source data but uses command line prompts

Initial Source ticker information

---

.idea/.gitignore
src/main.go

Made stock struct to hold different attributes for each stock
Made data structure to hold stock for each person. 
Single update at a time for new data 
TODO->add history for the previous times

Leo-dev Main structures for stock collection

---

stock_simulation/src/pages/ContactPage.tsx
stock_simulation/src/pages/LogInPage.tsx
stock_simulation/src/pages/pageStyles.css

Fixed sizing bug on contact us page and copied style to login page for consistency.

Formatted login page and contact us

---

Sprint1.md

Updated the issues that were completed

Update to sprint1.md

---

stock_simulation/src/App.tsx
stock_simulation/src/navbar.json
stock_simulation/src/pages/Search.tsx
stock_simulation/src/pages/pageStyles.css
stock_simulation/src/styles.css

Create Search bar and button to search for specific stock

Added Search Page

---

src/main.go

Rough version of getting old data for graphing.

Added old history data

---

stock_simulation/src/App.tsx
stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/LogInPage.tsx

Redirects to dashboard after login and allows users to search for a specific stock from the search bar

Created Search page and redirect to dashbaordf

---

src/main.go
src/main_worklist_funcs.go
stock_simulation/src/App.tsx
stock_simulation/src/index.ts
stock_simulation/src/pages/Search.tsx

Working integration between back end and front end

Integration between Backend and Front end

---

src/main.go
src/main_worklist_funcs.go

Rough version of getting old data for graphing.

Main structures added

---

src/main.go
src/main_worklist_funcs.go

Reverts MaxEpstein/Spring23CEN3031#38

Revert "Main structures added"

---

stock_simulation/src/index.tsx
stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/LogInPage.tsx
stock_simulation/src/pages/dash.css
stock_simulation/src/server.ts

Login now redirects to dashboard and there is some basic information.

Started Dashboard, Login correctly redirects

---

stock_simulation/src/pages/Search.tsx
stock_simulation/src/server.ts

If user searches for an invalid ticker they are now presented with such information.

Invalid Ticker Message

---

stock_simulation/src/pages/Search.tsx

Graphs on search work with data.

working graphs on Search

---

Sprint3.md
stock_simulation/src/pages/Search.tsx
stock_simulation/src/pages/pageStyles.css
stock_simulation/src/server.ts

Changed styling on graph search buttons

Updated Buttons on Search Graph

---

src/worklistFunctions.go
stock_simulation/src/pages/Search.tsx

Working Graphs with all

---

src/worklistFunctions.go
stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/Search.tsx

Invalid Ticker message now shows up as intended

Fixed invalid stock ticker message

---

stock_simulation/src/pages/LogInPage.tsx

Updated the login page to have a sign up and a login button.

Update to login page

---

stock_simulation/src/pages/Dash.tsx

Stock prices are now present on dashboard and are updated to most current price.

Updated stock prices on dashboard

---

stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/dash.css

Updated dash css for the new saved stocks

Update dash css

---

stock_simulation/src/pages/pageStyles.css

Buttons are animated on hover and press

button animation

---

stock_simulation/src/pages/Search.tsx

Upon graph update, stock info now pulls latest price instead of latest graph price (day's open on all intervals other than 1day)

Stock information now is the current price at the top

---

stock_simulation/src/pages/Dash.tsx

Dashboard only checks for new prices if the market is open

Updating on Dashboard Conditionals

---

Sprint4.md

Sprint 4 File Creation

---

src/searchServer.go
stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/Search.tsx

Can no longer manually redirect to the dashboard as it will redirect you back to the login page.

Logged in conditionals

---

src/searchServer.go
src/unitTests.go
src/userDatabase.go
stock_simulation/src/pages/Dash.tsx
stock_simulation/src/pages/Search.tsx
stock_simulation/src/pages/dash.css

Saved stocks now returns the correct thing from database and displays on dashboard

Updated Saved Stocks

---

stock_simulation/src/pages/Search.tsx

Updated search page conditionals for logged in

Updated search page conditionals
